//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCobro
    {
        public int id { get; set; }
        public int id_cobranza { get; set; }
        public int id_medicamento { get; set; }
        public double Importe { get; set; }
        public int Cantidad { get; set; }
        public double Subtotal { get; set; }
    
        public virtual Cobranza Cobranza { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
