//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamento()
        {
            this.DetalleCobro = new HashSet<DetalleCobro>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Compuesto { get; set; }
        public string Presentacion { get; set; }
        public string Gramaje { get; set; }
        public string Descripcion { get; set; }
        public string Laboratorio { get; set; }
        public double Precio { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public double Costo { get; set; }
        public string Lote { get; set; }
        public string Caducidad { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> CodigoBarra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCobro> DetalleCobro { get; set; }
    }
}
