//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string CodigoPostal { get; set; }
        public string Colonia { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string Contacto { get; set; }
        public string Email { get; set; }
        public string activo { get; set; }
    }
}
