//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioMedico.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tomasignos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<int> talla { get; set; }
        public string tensionArterial { get; set; }
        public Nullable<int> pulso { get; set; }
        public Nullable<int> fCardiaca { get; set; }
        public Nullable<int> frespiratoria { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public string alergias { get; set; }
        public string pbdx { get; set; }
    }
}
