//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza
    {
        public Cobranza()
        {
            this.DetalleCobro = new HashSet<DetalleCobro>();
        }
    
        public int id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Concepto { get; set; }
        public double Total { get; set; }
        public string TotalenLetra { get; set; }
        public int id_usuario { get; set; }
        public bool StatusCancel { get; set; }
        public int id_paciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<DetalleCobro> DetalleCobro { get; set; }
    }
}
