//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int id { get; set; }
        public int id_doctor { get; set; }
        public int id_paciente { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<double> Talla { get; set; }
        public Nullable<int> Pulso { get; set; }
        public Nullable<int> FreCardiaca { get; set; }
        public Nullable<int> FrecResp { get; set; }
        public Nullable<int> Temperatura { get; set; }
        public string Alergias { get; set; }
        public string PbDx { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
