//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCobro
    {
        public int id { get; set; }
        public int id_cobranza { get; set; }
        public int id_medicamento { get; set; }
        public double Importe { get; set; }
        public int Cantidad { get; set; }
        public double Subtotal { get; set; }
    
        public virtual Cobranza Cobranza { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
    }
}
