//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctores
    {
        public Doctores()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public int CedProfesional { get; set; }
        public string Estudio { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
