//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Cobranza = new HashSet<Cobranza>();
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Domicilio { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> CodPost { get; set; }
        public Nullable<int> telefono { get; set; }
    
        public virtual ICollection<Cobranza> Cobranza { get; set; }
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
